### ISSUE TITLE
Exception is throw if `Checking if blocking builds are queued` textbox is empty

### ISSUE THREAD

**Issue by nobitagamer** [huserben/TfsExtensions#4]
The following exception is throw then i checked `Enable Build In Queue Condition` and `Include current Build Definition as blocking Build` but leave the `Blocking Build Definitions` empty:
`2017-05-08T03:16:30.6976317Z Checking Build Definition: 
2017-05-08T03:16:30.9518036Z ##[error]System.Net.WebException: The remote server returned an error: (400) Bad Request.
2017-05-08T03:16:30.9518036Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-05-08T03:16:30.9518036Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-05-08T03:16:30.9557150Z ##[error]System.Management.Automation.RuntimeException: Cannot index into a null array.
2017-05-08T03:16:30.9557150Z    at CallSite.Target(Closure , CallSite , Object , Int32 )
2017-05-08T03:16:30.9557150Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2017-05-08T03:16:30.9557150Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2017-05-08T03:16:30.9557150Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-05-08T03:16:31.2134802Z None of the blocking builds is queued - proceeding`

**Comment by huserben** [comment]
Hi

I was able to reproduce this problem. But for me it basically happens aswell if the textbox is not empty, I'm having problems locating the actual issue, as it works if I run locally just the powershell script, but with the same parameters it seems to fail on VSTS...
I will further investigate, but I will not have time the next few days to invest much time.

**Comment by huserben** [comment]
Hi there
I found some minutes today anyway to check and found the issue. The newest version should fix your problem. Can you please quickly confirm so that I can close the issue.

Thanks 👍

**Comment by nobitagamer** [comment]
Nice, thanks!
