### ISSUE TITLE
Fail with collection name with space 

### ISSUE THREAD

**Issue by G100g** [huserben/TfsExtensions#70]
Hi,
 thank you for your extension.

I'm using it on our projects, but if a collection has a space in the name,
the path to the api will be created with a mistake

ex.
https://tfsaxel.domain.loc/My%20Project/projectname/_apis/build/definitions?api-version=2.0&name=build-definition-name

Become

https://tfsaxel.domain.loc/My%2520Project/projectname/_apis/build/definitions?api-version=2.0&name=build-definition-name

The %20 in the url, will be changed converting % char to %25.

Adding the full path to the collection/project work as workaround.

Maybe the root cause is here
https://github.com/huserben/TfsExtensions/blob/79fdff8140edb2c28e367a7119ea7fac09d81288/BuildTasks/triggerbuildtask/taskrunner.ts#L319

And the path from the environment variables had to be escaped...

Thank you

**Comment by huserben** [comment]
Hi @G100g 

thanks for the report. Are you using the option to specify the url on your own instead of the using the same team project as the build is in? Because for those cases it should work as my own test collection does have spaces and this is working fine up until now at least.

**Comment by G100g** [comment]
Yes, using "URL to TFS Server" option work perfectly.

**Comment by huserben** [comment]
So then you paste the URL with the already escaped spaces in there? If so, could you try without the spaces?

**Comment by G100g** [comment]
I used the url with escaped space and not

https://tfsaxel.domain.loc/My%20Project/projectname/
https://tfsaxel.domain.loc/My Project/projectname/

Works both.

**Comment by G100g** [comment]
Here the log

```
2018-04-30T14:55:46.4214878Z ==============================================================================
2018-04-30T14:55:46.4214878Z Task         : Trigger Build
2018-04-30T14:55:46.4214878Z Description  : This tasks allows to trigger a new Build (add it to the queue) as part of a Build Definition. It contains as well some conditions that can be applied, for example if the last build of certain definition was successful or not.
2018-04-30T14:55:46.4214878Z Version      : 2.8.2
2018-04-30T14:55:46.4214878Z Author       : Benjamin Huser
2018-04-30T14:55:46.4214878Z Help         : 
2018-04-30T14:55:46.4214878Z ==============================================================================
2018-04-30T14:55:46.9206886Z Using current Team Project Url
2018-04-30T14:55:46.9206886Z Path to Server: https://tfsaxel.domain.loc/My%20Project/projectname
2018-04-30T14:55:46.9206886Z Trying to fetch authentication token from system...
2018-04-30T14:55:46.9206886Z Using OAuth Access Token
2018-04-30T14:55:46.9206886Z Build shall be triggered for same user that triggered current build: Giorgio Aquino
2018-04-30T14:55:46.9206886Z Using same branch as source version: refs/heads/master
2018-04-30T14:55:46.9986888Z Request was not successful.
2018-04-30T14:55:46.9986888Z { Error: Not Found
2018-04-30T14:55:46.9986888Z     at ResponseError (W:\Agents\BuildAgent01\_work\_tasks\TriggerBuild_32abcf98-0df6-4711-b2e4-66a405d3c1a6\2.8.2\node_modules\web-request\index.js:146:9)
2018-04-30T14:55:46.9986888Z     at Request.request [as _callback] (W:\Agents\BuildAgent01\_work\_tasks\TriggerBuild_32abcf98-0df6-4711-b2e4-66a405d3c1a6\2.8.2\node_modules\web-request\index.js:58:28)
2018-04-30T14:55:46.9986888Z     at Request.self.callback (W:\Agents\BuildAgent01\_work\_tasks\TriggerBuild_32abcf98-0df6-4711-b2e4-66a405d3c1a6\2.8.2\node_modules\request\request.js:186:22)
2018-04-30T14:55:46.9986888Z     at emitTwo (events.js:106:13)
2018-04-30T14:55:46.9986888Z     at Request.emit (events.js:191:7)
2018-04-30T14:55:46.9986888Z     at Request.<anonymous> (W:\Agents\BuildAgent01\_work\_tasks\TriggerBuild_32abcf98-0df6-4711-b2e4-66a405d3c1a6\2.8.2\node_modules\request\request.js:1163:10)
2018-04-30T14:55:46.9986888Z     at emitOne (events.js:96:13)
2018-04-30T14:55:46.9986888Z     at Request.emit (events.js:188:7)
2018-04-30T14:55:46.9986888Z     at IncomingMessage.<anonymous> (W:\Agents\BuildAgent01\_work\_tasks\TriggerBuild_32abcf98-0df6-4711-b2e4-66a405d3c1a6\2.8.2\node_modules\request\request.js:1085:12)
2018-04-30T14:55:46.9986888Z     at IncomingMessage.g (events.js:292:16)
2018-04-30T14:55:46.9986888Z   response: 
2018-04-30T14:55:46.9986888Z    Response {
2018-04-30T14:55:46.9986888Z      request: 
2018-04-30T14:55:46.9986888Z       Request {
2018-04-30T14:55:46.9986888Z         domain: null,
2018-04-30T14:55:46.9986888Z         _events: [Object],
2018-04-30T14:55:46.9986888Z         _eventsCount: 5,
2018-04-30T14:55:46.9986888Z         _maxListeners: undefined,
2018-04-30T14:55:46.9986888Z         headers: [Object],
2018-04-30T14:55:46.9986888Z         agentOptions: [Object],
2018-04-30T14:55:46.9986888Z         encoding: 'utf-8',
2018-04-30T14:55:46.9986888Z         throwResponseError: true,
2018-04-30T14:55:46.9986888Z         uri: [Object],
2018-04-30T14:55:46.9986888Z         callback: [Function],
2018-04-30T14:55:46.9986888Z         readable: true,
2018-04-30T14:55:46.9986888Z         writable: true,
2018-04-30T14:55:46.9986888Z         _qs: [Object],
2018-04-30T14:55:46.9986888Z         _auth: [Object],
2018-04-30T14:55:46.9986888Z         _oauth: [Object],
2018-04-30T14:55:46.9986888Z         _multipart: [Object],
2018-04-30T14:55:46.9986888Z         _redirect: [Object],
2018-04-30T14:55:46.9986888Z         _tunnel: [Object],
2018-04-30T14:55:46.9986888Z         setHeader: [Function],
2018-04-30T14:55:46.9986888Z         hasHeader: [Function],
2018-04-30T14:55:46.9986888Z         getHeader: [Function],
2018-04-30T14:55:46.9986888Z         removeHeader: [Function],
2018-04-30T14:55:46.9986888Z         method: 'GET',
2018-04-30T14:55:47.0142888Z         localAddress: undefined,
2018-04-30T14:55:47.0142888Z         pool: [Object],
2018-04-30T14:55:47.0142888Z         dests: [],
2018-04-30T14:55:47.0142888Z         __isRequestRequest: true,
2018-04-30T14:55:47.0142888Z         _callback: [Function],
2018-04-30T14:55:47.0142888Z         proxy: null,
2018-04-30T14:55:47.0142888Z         tunnel: true,
2018-04-30T14:55:47.0142888Z         setHost: true,
2018-04-30T14:55:47.0142888Z         originalCookieHeader: undefined,
2018-04-30T14:55:47.0142888Z         _disableCookies: true,
2018-04-30T14:55:47.0142888Z         _jar: undefined,
2018-04-30T14:55:47.0142888Z         port: 443,
2018-04-30T14:55:47.0142888Z         host: 'tfsaxel.domain.loc',
2018-04-30T14:55:47.0142888Z         path: '/Axel%2520Project/projectname/_apis/build/definitions?api-version=2.0&name=projectname-Web-CI',
2018-04-30T14:55:47.0142888Z         _json: true,
2018-04-30T14:55:47.0142888Z         httpModule: [Object],
2018-04-30T14:55:47.0142888Z         agentClass: [Object],
2018-04-30T14:55:47.0142888Z         agent: [Object],
2018-04-30T14:55:47.0142888Z         options: [Object],
2018-04-30T14:55:47.0142888Z         response: [Object],
2018-04-30T14:55:47.0142888Z         _started: true,
2018-04-30T14:55:47.0142888Z         href: 'https://tfsaxel.domain.loc/My%2520Project/projectname/_apis/build/definitions?api-version=2.0&name=projectname-Web-CI',
2018-04-30T14:55:47.0142888Z         req: [Object],
2018-04-30T14:55:47.0142888Z         ntick: true,
2018-04-30T14:55:47.0142888Z         originalHost: 'tfsaxel.domain.loc',
2018-04-30T14:55:47.0142888Z         originalHostHeaderName: 'host',
2018-04-30T14:55:47.0142888Z         responseContent: [Object],
2018-04-30T14:55:47.0142888Z         _destdata: true,
2018-04-30T14:55:47.0142888Z         _ended: true,
2018-04-30T14:55:47.0142888Z         _callbackCalled: true },
2018-04-30T14:55:47.0142888Z      message: 
2018-04-30T14:55:47.0142888Z       IncomingMessage {
2018-04-30T14:55:47.0142888Z         _readableState: [Object],
2018-04-30T14:55:47.0142888Z         readable: false,
2018-04-30T14:55:47.0142888Z         domain: null,
2018-04-30T14:55:47.0142888Z         _events: [Object],
2018-04-30T14:55:47.0142888Z         _eventsCount: 4,
2018-04-30T14:55:47.0142888Z         _maxListeners: undefined,
2018-04-30T14:55:47.0142888Z         socket: [Object],
2018-04-30T14:55:47.0142888Z         connection: [Object],
2018-04-30T14:55:47.0142888Z         httpVersionMajor: 1,
2018-04-30T14:55:47.0142888Z         httpVersionMinor: 1,
2018-04-30T14:55:47.0142888Z         httpVersion: '1.1',
2018-04-30T14:55:47.0142888Z         complete: true,
2018-04-30T14:55:47.0142888Z         headers: [Object],
2018-04-30T14:55:47.0142888Z         rawHeaders: [Object],
2018-04-30T14:55:47.0142888Z         trailers: {},
2018-04-30T14:55:47.0142888Z         rawTrailers: [],
2018-04-30T14:55:47.0142888Z         upgrade: false,
2018-04-30T14:55:47.0142888Z         url: '',
2018-04-30T14:55:47.0142888Z         method: null,
2018-04-30T14:55:47.0142888Z         statusCode: 404,
2018-04-30T14:55:47.0142888Z         statusMessage: 'Not Found',
2018-04-30T14:55:47.0142888Z         client: [Object],
2018-04-30T14:55:47.0142888Z         _consuming: true,
2018-04-30T14:55:47.0142888Z         _dumped: false,
2018-04-30T14:55:47.0142888Z         req: [Object],
2018-04-30T14:55:47.0142888Z         request: [Object],
2018-04-30T14:55:47.0142888Z         toJSON: [Function: responseToJSON],
2018-04-30T14:55:47.0142888Z         caseless: [Object],
2018-04-30T14:55:47.0142888Z         read: [Function],
2018-04-30T14:55:47.0142888Z         body: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>404 - Impossibile trovare il file o la directory.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Errore del server</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>404 - Impossibile trovare il file o la directory.</h2>\r\n  <h3>� possibile che la risorsa desiderata sia stata rimossa, che sia temporaneamente non disponibile o che il relativo nome sia stato modificato.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n' },
2018-04-30T14:55:47.0142888Z      body: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>404 - Impossibile trovare il file o la directory.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Errore del server</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>404 - Impossibile trovare il file o la directory.</h2>\r\n  <h3>� possibile che la risorsa desiderata sia stata rimossa, che sia temporaneamente non disponibile o che il relativo nome sia stato modificato.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n' },
2018-04-30T14:55:47.0142888Z   statusCode: 404 }
2018-04-30T14:55:47.0142888Z Authentication failed - please make sure your settings are correct.
2018-04-30T14:55:47.0142888Z If you use the OAuth Token, make sure you enabled the access to it on the Build Definition.
2018-04-30T14:55:47.0142888Z If you use a Personal Access Token, make sure it did not expire.
2018-04-30T14:55:47.0142888Z If you use Basic Authentication, make sure alternate credentials are enabled on your TFS/VSTS.
2018-04-30T14:55:47.0142888Z ##[error]Authentication with TFS Server failed. Please check your settings.
```

**Comment by G100g** [comment]
and yes, only if a don't specify the full URL

![image](https://user-images.githubusercontent.com/1582583/39437162-54eaf616-4ca0-11e8-954d-3265f356bc14.png)

**Comment by huserben** [comment]
Ok, I cross checked and with my test server it's behaving differently as it's not returning me the escaped url from the environment variable but one with spaces.

I will have a closer look and probably need to build in some handling for both cases.
I'm not sure yet when I will find the time to do so, but I  hope you can use the manual URL as a work-around for the time being.

**Comment by huserben** [comment]
Hi @G100g 

I uploaded version 2.8.4 of the Task which should include a fix for your issue.
Would you please verify if it works or not and give me a feedback here?

**Comment by G100g** [comment]
Wow. Thank you.
Today is holiday in Italy, tomorrow I will test your update in my office and I'll give you a feedback.

Best.

**Comment by G100g** [comment]
Hi,
 tested new release and I confirm the task work properly now.

Thank you!

**Comment by huserben** [comment]
Very good.

In case you find any other problems, or you have an idea on how to improve the task, please don't hesitate to open another issue. Thank you very much for your feedback.
